services:
  redmine:
    image: redmine:6.0.4
    ports:
      - "80:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
    volumes:
      - redmine_files:/usr/src/redmine/files
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  task-scheduler:
    build:
      context: ./task-scheduler
    volumes:
      - ./task-scheduler/data:/app/data
      - ./task-scheduler/logs:/app/logs
    tty: true
    environment:
      REDMINE_URL: http://redmine:3000
      REDMINE_API_KEY: ${REDMINE_API_KEY}
      DB_HOST: db
      DB_NAME: redmine
      DB_USER: redmine
      DB_PASSWORD: redmine_password
    depends_on:
      - redmine
      - db

volumes:
  redmine_files:
  postgres_data:
